# Generated by Django 4.0.3 on 2022-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('fechaNacimiento', models.DateField()),
                ('dni', models.IntegerField()),
            ],
        ),
    ]
